"""create_initial_tables

Revision ID: 98dc6b785c31
Revises:
Create Date: 2026-07-19 10:37:13.041773

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision = "98dc6b785c31"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pirometro",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("nome", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("setor", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("material_alvo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("processo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("molde", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "codigo_pirometro",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pirometro_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("codigo", sa.Integer(), nullable=False),
        sa.Column("etapa_nome", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("descricao", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("temp_min_esperada", sa.Float(), nullable=True),
        sa.Column("temp_max_esperada", sa.Float(), nullable=True),
        sa.Column("ordem_no_processo", sa.Integer(), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pirometro_id"],
            ["pirometro.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "leitura",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pirometro_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("codigo_pirometro_id", sa.Integer(), nullable=False),
        sa.Column("temperatura_lida", sa.Float(), nullable=False),
        sa.Column("operador_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("corrida_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("lote_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("panela_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("observacao", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["codigo_pirometro_id"],
            ["codigo_pirometro.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pirometro_id"],
            ["pirometro.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("leitura")
    op.drop_table("codigo_pirometro")
    op.drop_table("pirometro")
    # ### end Alembic commands ###
